### ISSUE TITLE
[$100] Make Loading logo animation with path adobe after effect

### ISSUE THREAD

**Issue by YudhaDM19** [topcoder-platform/thrive-submit#312] opened 2020-12-04 07:27 UTC
**Track** : Design
**Author:** Yudha19 

https://drive.google.com/drive/folders/14yq8Kd6bmj90cECCh12JkgXRtCuAznpC?usp=sharing

**Comment by kkartunov** [comment] 2020-12-04 09:20
@YudhaDM19 we can't access that doc, can you open it for reading?

**Comment by YudhaDM19** [comment] 2020-12-04 09:42
Yes i can see
Please follow linkhttps://drive.google.com/folderview?id=14yq8Kd6bmj90cECCh12JkgXRtCuAznpC

Dikirim dari Yahoo Mail di Android 
 
  Pada Jum, 4 Des 2020 pada 16:20, Kiril Kartunov<notifications@github.com> menulis:   


@YudhaDM19 we can't access that doc, can you open it for reading?

**Comment by YudhaDM19** [comment] 2020-12-04 11:07
Yes i can read

Dikirim dari Yahoo Mail di Android 
 
  Pada Jum, 4 Des 2020 pada 16:20, Kiril Kartunov<notifications@github.com> menulis:   


@YudhaDM19 we can't access that doc, can you open it for reading?

**Comment by fajarmln** [comment] 2020-12-04 11:10
YudhaDM19, 

You need to give a view access to the docs, right now it's restricted only to the owner (yourself)

**Comment by YudhaDM19** [comment] 2020-12-04 11:38
well I have opened the access,
Sorry, I forgot.

https://drive.google.com/drive/folders/14yq8Kd6bmj90cECCh12JkgXRtCuAznpC?usp=sharing

**Comment by kkartunov** [comment] 2020-12-07 13:34
@YudhaDM19 your article needs to be > 500 words and pass the Plagiarism checker which it fails. https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYCqA7AazyQHc8wAaMBFJAVwAcswBlBuAGw4Es8FLIsRKjQAJOgFso5bPiKk8AAhKoAJgGcBEenhhYAjAF8K4aPGTpmAWW7r17LnFUCa9JtjacefLUItjJaWtbey8nZTVNKm06XSwAJmNTPxFmAAUoO24ANzgANSRuCDgXWkZmFhg0DhLolPRxKRkwDKzcxWzC4sUJWzp1WsgdPUwjE0FzVOw0jigEbigUWwlSt3TZ%2BcXl30mGwOb8VG55vCgORW1dODjo4YSkieFLbAAxVCkYGF5%2BKldyjyqNR2TwCTWYAEkJAxaOwUIoAGbvWBfHy3WIjMbJXYYbAAdTUAGEABZdQZ-dxgACieCJ0mKEmuejq2MaQTxaguJKKgxicVGhgAukA&page=plagiarism&breadcrumbs=true

Please, fix and resubmit.

**Comment by YudhaDM19** [comment] 2020-12-07 13:36
Ok, thank you

**Comment by YudhaDM19** [comment] 2020-12-07 16:42
**Trek** : Desain
**Penulis** : Yudha19

https://drive.google.com/drive/folders/14yq8Kd6bmj90cECCh12JkgXRtCuAznpC?usp=sharing

**Comment by kkartunov** [comment] 2020-12-09 09:02
Thanks, @YudhaDM19 it passes min checks now.

**Comment by YudhaDM19** [comment] 2020-12-17 07:26
thank you

**Comment by Dara-K** [comment] 2020-12-23 20:49
@YudhaDM19  Please give me edit access, I'd like to add comments to your article.

**Comment by YudhaDM19** [comment] 2020-12-23 22:32
ok DaraK

**Comment by YudhaDM19** [comment] 2020-12-24 00:58
hi @Dara-K thanks for your advice. I've finished fixing it.

**Comment by fajarmln** [comment] 2020-12-24 06:04
Hi @YudhaDM19 

Here is my comments regarding your article: 

1# Intro to the article, does the purpose of animation only to make it more 'interesting'? What is the main purpose of animation in the web? needs to clear this out 

2# Please remove this "Here I will share a little of my knowledge, about the after effect, and maybe on another occasion, I will share another tutorial. Pay attention to my tutorial below.", make the article general without your point of view


3# All images should clearly show how the step by step tutorials, for example, when you are asking the viewer to choose ellipse tool, highlight the ellipse tool position in your image

4# "Step 2" to "Step 3", in step 2 you only ask viewer to choose ellipse tool, but in step 3 you are asking them to duplicate the circle, while you never ask them to create a circle, make the instructions clear

5# Step 4, where can the viewer change the circle name?

6# Please provide some brief about adobe after effects layout so the viewer can easily find items that you refer in the tutorial

7# Step 7 is not clear, What is "Point of Frame"? What is the purpose of Keyframe Assistant, etc....

8# Step 9, This step is not clear, what is the purpose of this step? 

9# Step 10, its too fast, clearly describe the purpose of each step here

10# The content writing in this tutorial article is not appealing, need better writing approach to make it more interesting for the viewer/reader

Please fix all those issues, Thank you.

**Comment by YudhaDM19** [comment] 2020-12-24 06:12
Ok @fajarmln thank you

**Comment by Dara-K** [comment] 2020-12-24 09:02
Thanks @fajarmln! 

Yeah, we need more context for the steps @YudhaDM19 as I was mentioning in the article too. Try to explain what the user will do in each step and why and then show the technical part.

**Comment by fajarmln** [comment] 2020-12-25 04:34
@YudhaDM19 please let us know if you have updated the article so we can check again, thank you.

**Comment by YudhaDM19** [comment] 2020-12-25 07:45
thank you @fajarmln , I've tried to fix it, you can check again.

thank you.

https://drive.google.com/drive/folders/14yq8Kd6bmj90cECCh12JkgXRtCuAznpC?usp=sharing

**Comment by fajarmln** [comment] 2020-12-25 09:41
@YudhaDM19 I provide some comments in the article, please check and apply it, thank you.

**Comment by YudhaDM19** [comment] 2020-12-25 11:38
Hi @fajarmln @Dara-K , thank you for the advice, I have answered and fixed it.
but if my article is useless or bad, I will delete it.
thank you.

**Comment by fajarmln** [comment] 2020-12-26 00:32
Thank you @YudhaDM19, your article is okay and we actually need after effect in Thrive since 2021 might have more opportunity for this kind of challenge. 

However, since this is a beginner tutorial, you need to flesh out all the details, you need to explain the after effect workspace and its features, need to provide the context of each step in the article, and we will need detailed configuration for each steps that can be easily reproduce by the viewer. 

Think of the reader/viewer perspective, think when you are in their position, will you be able to easily understand your article?

**Comment by YudhaDM19** [comment] 2020-12-26 00:37
maybe i need to make a basic after effects tutorial? For example, the layout of the tools in the after effect?

**Comment by fajarmln** [comment] 2020-12-26 00:55
You can create it in a different article (the new one, complete tools, and workspace for after effect), for this one, explain the layout and workspace that related to your animation tutorial, let's finish this one and create a new one after that, thank you.

**Comment by YudhaDM19** [comment] 2020-12-26 01:12
ok, I updated it, please check it again.

**Comment by fajarmln** [comment] 2020-12-26 01:16
@YudhaDM19, Please take your time to update the article, you are constantly in a rush to update it and the result is not good and unable to accommodate our request. Make sure to understand what quality we want in your article, I've provided my feedback in the article.

**Comment by YudhaDM19** [comment] 2020-12-27 06:12
Hi @fajarmln I've fixed it, you try to correct it.

Thank you

**Comment by fajarmln** [comment] 2020-12-27 07:18
@YudhaDM19 can you check again, there are several comments that not being applied.

**Comment by YudhaDM19** [comment] 2020-12-28 11:49
I've tried to improve my article. hopefully according to your expectations.

**Comment by YudhaDM19** [comment] 2020-12-28 11:49
Hi @fajarmln 
I've tried to improve my article. hopefully according to your expectations.

**Comment by Dara-K** [comment] 2020-12-29 13:48
Hi @YudhaDM19 

Thank you for updating. I have added some comments in your article.

**Comment by YudhaDM19** [comment] 2020-12-31 00:26
hi @Dara-K I've fixed it, you can now check it.

**Comment by fajarmln** [comment] 2021-01-02 12:35
I am making some edits in your docs and also suggest some of content revision, please check. Let's use the google docs version from now on: 

https://docs.google.com/document/d/1HgEXJ2YJIf6KHupu6bPKmVCj212azeahy71bT9Dp1vs/edit?usp=sharing

**Comment by YudhaDM19** [comment] 2021-01-02 12:41
Ok @fajarmln thanks

**Comment by YudhaDM19** [comment] 2021-01-04 05:06
hello @fajarmln , sorry I just finished repairing, because yesterday I was busy.
please check my article again.

**Comment by Dara-K** [comment] 2021-01-04 09:13
I added some more comments and edits @YudhaDM19 Please take a look

**Comment by YudhaDM19** [comment] 2021-01-05 09:47
thanks @Dara-K  for the advice, I've edited, please check again.

**Comment by Dara-K** [comment] 2021-01-05 14:18
Looks good by me.

@fajarmln, if you have any other comments, feel free to add them, else we can approve this

**Comment by YudhaDM19** [comment] 2021-01-08 06:41
thank you @Dara-K

**Comment by fajarmln** [comment] 2021-01-08 22:00
@YudhaDM19, there are tons of grammar and language structure that needs to be revised, but considering the amount of time we've spent on this one article, I am jumping in and edit your article directly so it will be easier for the viewer to read it: 

https://docs.google.com/document/d/1HgEXJ2YJIf6KHupu6bPKmVCj212azeahy71bT9Dp1vs/edit

The article looks fine now, I will approve it.

**Comment by YudhaDM19** [comment] 2021-01-09 00:37
Thank you @fajarmln

**Comment by YudhaDM19** [comment] 2021-01-12 03:31
hi @fajarmln @Dara-K , what should i do after this? do I have to click close issue?

**Comment by kkartunov** [comment] 2021-01-12 10:10
Contest https://www.topcoder.com/challenges/30161987 has been created for this ticket.<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Comment by kkartunov** [comment] 2021-01-12 10:11
@YudhaDM19, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Comment by YudhaDM19** [comment] 2021-01-12 13:35
I have registered in topcoder x, but I can't log in, just keep loading. @kkartunov

**Comment by kkartunov** [comment] 2021-01-13 07:38
@YudhaDM19, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Comment by kkartunov** [comment] 2021-01-14 15:40
@YudhaDM19, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Comment by kkartunov** [comment] 2021-01-15 08:01
Contest https://www.topcoder.com/challenges/30161987 has been updated - it has been assigned to Yudha19.<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Comment by kkartunov** [comment] 2021-01-15 13:49
Published https://www.topcoder.com/thrive/articles/using-trim-paths-in-after-effects-to-create-simple-animation
Thank you @YudhaDM19

**Comment by kkartunov** [comment] 2021-01-15 13:49
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30161987<br/><br/>```This is an automated message for kiril.kartunov via Topcoder X```

**Closed by kkartunov** 2021-01-15 13:49 UTC
Labels: Design, Passed Review, Published, tcx_Assigned, tcx_FixAccepted
