### ISSUE TITLE
Getting started with Jupyter notebook

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#86] opened 2019-12-15 06:51 UTC
Category: Data Science

[getting_started_jupyter.md.zip](https://github.com/topcoder-platform/thrive-submit/files/3964661/getting_started_jupyter.md.zip)

**Comment by kkartunov** [comment] 2019-12-15 13:32
passed PCheck and min length check.

**Comment by harshitmehta123** [comment] 2019-12-17 05:02
Duplicate of #64 
@anu0012 to merge with #64

**Closed by harshitmehta123** 2019-12-17 05:02 UTC
Labels: Data Science, Ready For Review
